### ISSUE TITLE
Error during redisplay

### ISSUE THREAD

**Issue by tomek-railwaymen** [nex3/sass-mode#20]
When I open a sass file, I get the couple of messages like:
`Error during redisplay: (jit-lock-function 3245) signaled (no-catch --cl-block-nil-- t)`
Syntax highlighting is incomplete. Emacs version: 24.5.1

**Comment by purcell** [comment]
Please provide sample input, because if we can't reproduce this locally, it's not going to be easy to fix. Also, please confirm that you can reproduce this beginning with `emacs -Q`, i.e. eliminating all other packages which might possibly conflict. Thanks!

**Comment by tomek-railwaymen** [comment]
@purcell Thank you for quick response. `emacs -Q` doesn't cause any issues. Loading only sass-mode (which including haml-mode) does. Simple sample:
```sass
.viewport-content.readonly
  > div.pro-tables
    position: relative
    &:after
      content: "Read Only"
```
I tried sass-mode from melpa-stable and the latest version from melpa. I use emacs compiled from sources. Please let me know if you need more details.

**Comment by purcell** [comment]
Thanks! I just tried this with a recent Emacs snapshot and I can't reproduce it, so perhaps it's specific to that particular Emacs version? Also, you might experience problems due to using byte-compiled `.elc` files from a previous version of Emacs, so if you've recently upgraded, consider clearing out your `~/.emacs.d/elpa` folder.

**Comment by liZe** [comment]
I had the same problem and removing all the `.elc` files from the `elpa` folder fixed it. Thanks!
